USE [master]
GO

/****** Object:  Database [Social_Network]    Script Date: 3/1/2021 9:37:11 PM ******/
CREATE DATABASE [Social_Network]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Social_Network', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.KNIGHT2908\MSSQL\DATA\Social_Network.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Social_Network_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.KNIGHT2908\MSSQL\DATA\Social_Network_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Social_Network] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Social_Network].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Social_Network] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Social_Network] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Social_Network] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Social_Network] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Social_Network] SET ARITHABORT OFF 
GO

ALTER DATABASE [Social_Network] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Social_Network] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Social_Network] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Social_Network] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Social_Network] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Social_Network] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Social_Network] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Social_Network] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Social_Network] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Social_Network] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Social_Network] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Social_Network] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Social_Network] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Social_Network] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Social_Network] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Social_Network] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Social_Network] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Social_Network] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Social_Network] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Social_Network] SET  MULTI_USER 
GO

ALTER DATABASE [Social_Network] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Social_Network] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Social_Network] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Social_Network] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Social_Network] SET  READ_WRITE 
GO


USE [Social_Network]
GO

/****** Object:  Table [dbo].[Shop]    Script Date: 3/1/2021 9:37:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Shop](
	[Name] [varchar](225) NULL,
	[Address] [varchar](225) NULL,
	[Detail] [varchar](225) NULL,
	[Img] [varchar](225) NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ShopID]  AS ('Sh'+right('000'+CONVERT([varchar](4),[Id]),(5))),
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [Social_Network]
GO

/****** Object:  Table [dbo].[DonHang]    Script Date: 3/1/2021 9:34:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DonHang](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DhID]  AS ('DhId'+right('000'+CONVERT([varchar](5),[Id]),(7))) PERSISTED,
	[MaCuaHang] [varchar](225) NOT NULL,
	[Time_Plant] [varchar](225) NOT NULL,
	[Time_Delivery] [varchar](225) NULL,
	[Statu] [varchar](225) NULL,
	[Total] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[Type_User]    Script Date: 3/1/2021 9:38:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Type_User](
	[TypeID] [varchar](50) NOT NULL,
	[Name] [varchar](255) NULL,
	[Detail] [varchar](255) NULL,
 CONSTRAINT [PK_TypeID] PRIMARY KEY CLUSTERED 
(
	[TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [Social_Network]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 3/1/2021 9:38:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Users](
	[UserID] [varchar](50) NOT NULL,
	[TypeID] [varchar](50) NOT NULL,
	[Name] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [PK_UserID] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([TypeID])
REFERENCES [dbo].[Type_User] ([TypeID])
GO


